import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, getFirestore, limit, onSnapshot, orderBy, query, runTransaction, serverTimestamp, setDoc, updateDoc, where } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { user:null, merchant:null, store:null, storeId:null, products:[], orders:[], productFilter:'', orderFilter:'all', stockFilter:'all', unsubProducts:null, unsubOrders:null, location:null };

function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2800)}
function showScreen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id))}
function money(v){return `₹${Number(v||0).toLocaleString('en-IN')}`}
function stockState(p){if(Number(p.stockQuantity)<=0)return'out';if(Number(p.stockQuantity)<=Number(p.lowStockThreshold||5))return'low';return'ok'}
function openModal(id){$(`#${id}`).classList.add('open');$(`#${id}`).setAttribute('aria-hidden','false')}
function closeModal(id){$(`#${id}`).classList.remove('open');$(`#${id}`).setAttribute('aria-hidden','true')}

async function login(){try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await signInWithPopup(auth,provider)}catch(e){console.error(e);toast(e.code==='auth/unauthorized-domain'?'Add this Vercel domain in Firebase Authorized domains.':'Google login failed.',true)}}
async function logout(){state.unsubProducts?.();state.unsubOrders?.();await signOut(auth)}

async function loadMerchant(){const merchantSnap=await getDoc(doc(db,'merchants',state.user.uid));state.merchant=merchantSnap.exists()?merchantSnap.data():null;if(!state.merchant?.onboardingComplete)return false;state.storeId=state.merchant.storeId;const storeSnap=await getDoc(doc(db,'stores',state.storeId));state.store=storeSnap.exists()?storeSnap.data():null;return Boolean(state.store)}

function hydrateOnboarding(){ $('#owner-name').value=state.user.displayName||''; state.location=null }
function requestLocation(){if(!navigator.geolocation)return toast('Location is not supported.',true);$('#location-status').textContent='Detecting location…';navigator.geolocation.getCurrentPosition(p=>{state.location={latitude:Number(p.coords.latitude.toFixed(6)),longitude:Number(p.coords.longitude.toFixed(6)),accuracy:Math.round(p.coords.accuracy)};$('#location-status').textContent=`Location saved: ${state.location.latitude}, ${state.location.longitude}`;toast('Shop location added.')},()=>{state.location=null;$('#location-status').textContent='Location permission denied.';toast('Allow location access.',true)},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}

async function createBusiness(e){e.preventDefault();const phone=$('#owner-phone').value.replace(/\D/g,'');if(!/^[6-9]\d{9}$/.test(phone))return toast('Enter a valid 10-digit phone number.',true);if(!state.location)return toast('Add current shop location.',true);const btn=$('#complete-setup-btn');btn.disabled=true;btn.textContent='Creating…';try{const storeRef=doc(collection(db,'stores'));const now=serverTimestamp();const store={merchantId:state.user.uid,name:$('#shop-name').value.trim(),category:$('#shop-category').value,description:$('#shop-description').value.trim(),phone,address:{fullAddress:$('#shop-address').value.trim()},location:state.location,openingTime:$('#opening-time').value,closingTime:$('#closing-time').value,isOpen:true,isApproved:false,status:'pending_approval',minimumOrder:99,deliveryRadiusKm:8,rating:0,totalRatings:0,createdAt:now,updatedAt:now};const merchant={uid:state.user.uid,fullName:$('#owner-name').value.trim(),email:state.user.email||'',photoURL:state.user.photoURL||'',phone,storeId:storeRef.id,onboardingComplete:true,accountStatus:'pending',termsAccepted:true,createdAt:now,updatedAt:now};await setDoc(storeRef,store);await setDoc(doc(db,'merchants',state.user.uid),merchant);state.merchant=merchant;state.store=store;state.storeId=storeRef.id;hydrateApp();startRealtime();showScreen('app-screen');toast('Business profile created.')}catch(err){console.error(err);toast('Business profile could not be created. Check Firestore rules.',true)}finally{btn.disabled=false;btn.textContent='Create business profile'}}

function hydrateApp(){const name=state.store?.name||'MyQK Store';$('#header-store-name').textContent=name;$('#profile-store-name').textContent=name;$('#profile-owner-email').textContent=state.user.email||'—';$('#profile-avatar').textContent=name.charAt(0).toUpperCase();$('#profile-status').textContent=state.store?.isApproved?'Active store':'Pending approval';renderShopToggle()}
function renderShopToggle(){const b=$('#shop-toggle');const open=state.store?.isOpen!==false;b.textContent=open?'Open':'Closed';b.className=`status-toggle ${open?'open':'closed'}`}
async function toggleShop(){try{const next=!(state.store?.isOpen!==false);await updateDoc(doc(db,'stores',state.storeId),{isOpen:next,updatedAt:serverTimestamp()});state.store.isOpen=next;renderShopToggle();toast(next?'Store is open.':'Store is closed.')}catch(e){toast('Store status update failed.',true)}}

function startRealtime(){state.unsubProducts?.();state.unsubOrders?.();state.unsubProducts=onSnapshot(query(collection(db,'stores',state.storeId,'products'),orderBy('createdAt','desc')),snap=>{state.products=snap.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>{console.error(e);toast('Products could not load.',true)});state.unsubOrders=onSnapshot(query(collection(db,'orders'),where('storeId','==',state.storeId),limit(50)),snap=>{state.orders=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));renderAll()},e=>{console.error(e);toast('Orders could not load. Firestore rules/index may be missing.',true)})}
function renderAll(){renderStats();renderProducts();renderOrders();renderInventory();renderRecentOrders()}
function renderStats(){const completed=state.orders.filter(o=>o.status==='completed');const sales=completed.reduce((s,o)=>s+Number(o.subtotal||o.totalAmount||0),0);$('#today-sales').textContent=money(sales);$('#today-summary').textContent=`${completed.length} orders completed`;$('#new-orders-count').textContent=state.orders.filter(o=>o.status==='pending_merchant').length;$('#preparing-count').textContent=state.orders.filter(o=>['merchant_accepted','preparing'].includes(o.status)).length;$('#products-count').textContent=state.products.length;$('#low-stock-count').textContent=state.products.filter(p=>stockState(p)!=='ok').length}
function productCard(p,inventory=false){const s=stockState(p);if(inventory)return `<article class="inventory-card"><div class="card-head"><div><h4>${p.name}</h4><p>${p.unit||''} · ${p.category||''}</p></div><span class="stock-chip ${s}">${s==='ok'?'In stock':s==='low'?'Low stock':'Out of stock'}</span></div><div class="inventory-controls"><button data-stock="-1" data-id="${p.id}">−</button><strong>${Number(p.stockQuantity||0)}</strong><button data-stock="1" data-id="${p.id}">+</button><span>${money(p.sellingPrice)}</span></div></article>`;return `<article class="product-card"><div class="card-head"><div><h4>${p.name}</h4><p>${p.brand||'MyQK'} · ${p.unit||''}</p></div><div><div class="price">${money(p.sellingPrice)}</div><span class="stock-chip ${s}">${Number(p.stockQuantity||0)} left</span></div></div><div class="card-actions"><button data-edit-product="${p.id}">Edit</button><button data-toggle-product="${p.id}" class="${p.isActive===false?'danger':''}">${p.isActive===false?'Activate':'Disable'}</button></div></article>`}
function renderProducts(){const term=state.productFilter.toLowerCase();const list=state.products.filter(p=>!term||`${p.name} ${p.category} ${p.brand}`.toLowerCase().includes(term));$('#products-list').innerHTML=list.length?list.map(p=>productCard(p)).join(''):'<div class="empty-state">No products added yet.</div>'}
function renderInventory(){let list=state.products;if(state.stockFilter==='low')list=list.filter(p=>stockState(p)==='low');if(state.stockFilter==='out')list=list.filter(p=>stockState(p)==='out');$('#inventory-list').innerHTML=list.length?list.map(p=>productCard(p,true)).join(''):'<div class="empty-state">No products in this section.</div>'}
function statusLabel(s){return({pending_merchant:'New order',merchant_accepted:'Accepted',preparing:'Preparing',ready_for_pickup:'Ready for pickup',accepted:'Rider assigned',picked_up:'Picked up',completed:'Completed',merchant_rejected:'Rejected',cancelled:'Cancelled'})[s]||s}
function orderCard(o){return `<article class="order-card" data-order="${o.id}"><div class="card-head"><div><h4>Order #${o.orderNumber||o.id.slice(0,6)}</h4><p>${o.customerName||'Customer'} · ${o.itemCount||o.items?.length||0} items</p></div><span class="order-status">${statusLabel(o.status)}</span></div><div class="order-meta"><span>${o.paymentMode||'Cash on Delivery'}</span><strong>${money(o.totalAmount)}</strong></div></article>`}
function renderOrders(){const list=state.orderFilter==='all'?state.orders:state.orders.filter(o=>o.status===state.orderFilter);$('#orders-list').innerHTML=list.length?list.map(orderCard).join(''):'<div class="empty-state">No orders in this section.</div>'}
function renderRecentOrders(){const list=state.orders.slice(0,3);$('#recent-orders').innerHTML=list.length?list.map(orderCard).join(''):'No merchant orders yet.'}

function resetProductForm(){ $('#product-form').reset(); $('#product-id').value=''; $('#product-threshold').value='5'; $('#product-modal-title').textContent='Add product' }
function editProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;$('#product-id').value=id;$('#product-name').value=p.name||'';$('#product-category').value=p.category||'';$('#product-brand').value=p.brand||'';$('#product-unit').value=p.unit||'';$('#product-mrp').value=p.mrp||0;$('#product-price').value=p.sellingPrice||0;$('#product-stock').value=p.stockQuantity||0;$('#product-threshold').value=p.lowStockThreshold||5;$('#product-description').value=p.description||'';$('#product-modal-title').textContent='Edit product';openModal('product-modal')}
async function saveProduct(e){e.preventDefault();const id=$('#product-id').value;const data={storeId:state.storeId,merchantId:state.user.uid,name:$('#product-name').value.trim(),category:$('#product-category').value.trim(),brand:$('#product-brand').value.trim(),unit:$('#product-unit').value.trim(),mrp:Number($('#product-mrp').value),sellingPrice:Number($('#product-price').value),stockQuantity:Number($('#product-stock').value),lowStockThreshold:Number($('#product-threshold').value),description:$('#product-description').value.trim(),isActive:true,isAvailable:Number($('#product-stock').value)>0,updatedAt:serverTimestamp()};if(data.sellingPrice>data.mrp)return toast('Selling price cannot be higher than MRP.',true);try{if(id)await updateDoc(doc(db,'stores',state.storeId,'products',id),data);else await addDoc(collection(db,'stores',state.storeId,'products'),{...data,createdAt:serverTimestamp()});closeModal('product-modal');toast(id?'Product updated.':'Product added.')}catch(err){console.error(err);toast('Product save failed.',true)}}
async function toggleProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;try{await updateDoc(doc(db,'stores',state.storeId,'products',id),{isActive:p.isActive===false,updatedAt:serverTimestamp()})}catch(e){toast('Product status update failed.',true)}}
async function changeStock(id,delta){const ref=doc(db,'stores',state.storeId,'products',id);try{await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('NOT_FOUND');const before=Number(snap.data().stockQuantity||0);const after=Math.max(0,before+delta);tx.update(ref,{stockQuantity:after,isAvailable:after>0,updatedAt:serverTimestamp()});const movement=doc(collection(db,'stores',state.storeId,'stockMovements'));tx.set(movement,{productId:id,type:delta>0?'manual_add':'manual_remove',quantityChange:after-before,previousStock:before,newStock:after,createdBy:state.user.uid,createdAt:serverTimestamp()})})}catch(e){console.error(e);toast('Stock update failed.',true)}}

function openOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const items=(o.items||[]).map(i=>`<div class="order-item-row"><span>${i.quantity||1} × ${i.name}</span><strong>${money(i.lineTotal||Number(i.unitPrice||0)*Number(i.quantity||1))}</strong></div>`).join('');let actions='';if(o.status==='pending_merchant')actions='<div class="card-actions"><button data-order-action="merchant_rejected" data-id="'+id+'">Reject</button><button class="primary-action" data-order-action="merchant_accepted" data-id="'+id+'">Accept order</button></div>';if(o.status==='merchant_accepted')actions='<div class="card-actions"><button class="primary-action" data-order-action="preparing" data-id="'+id+'">Start preparing</button></div>';if(o.status==='preparing')actions='<div class="card-actions"><button class="primary-action" data-order-action="ready_for_pickup" data-id="'+id+'">Mark ready for pickup</button></div>';$('#order-detail-content').innerHTML=`<p><strong>${o.customerName||'Customer'}</strong><br>${o.drop?.address||o.dropAddress||''}</p><div class="order-items">${items||'No item details'}</div><div class="order-meta"><span>${statusLabel(o.status)}</span><strong>${money(o.totalAmount)}</strong></div>${actions}`;openModal('order-modal')}
async function orderAction(id,next){const ref=doc(db,'orders',id);try{await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('NOT_FOUND');const o=snap.data();if(o.storeId!==state.storeId||o.merchantId!==state.user.uid)throw new Error('DENIED');const allowed={pending_merchant:['merchant_accepted','merchant_rejected'],merchant_accepted:['preparing'],preparing:['ready_for_pickup']};if(!allowed[o.status]?.includes(next))throw new Error('INVALID_STATUS');const update={status:next,updatedAt:serverTimestamp()};if(next==='merchant_accepted')update.merchantAcceptedAt=serverTimestamp();if(next==='merchant_rejected')update.merchantRejectedAt=serverTimestamp();if(next==='preparing')update.preparingAt=serverTimestamp();if(next==='ready_for_pickup')update.readyAt=serverTimestamp();tx.update(ref,update)});closeModal('order-modal');toast(`Order marked ${statusLabel(next)}.`)}catch(e){console.error(e);toast('Order status update failed.',true)}}

function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#main-content').scrollTop=0}

document.addEventListener('click',e=>{const close=e.target.closest('[data-close-modal]');if(close)closeModal(close.dataset.closeModal);const nav=e.target.closest('[data-view]');if(nav)switchView(nav.dataset.view);const go=e.target.closest('[data-go]');if(go)switchView(go.dataset.go);const edit=e.target.closest('[data-edit-product]');if(edit)editProduct(edit.dataset.editProduct);const toggle=e.target.closest('[data-toggle-product]');if(toggle)toggleProduct(toggle.dataset.toggleProduct);const stock=e.target.closest('[data-stock]');if(stock)changeStock(stock.dataset.id,Number(stock.dataset.stock));const order=e.target.closest('[data-order]');if(order)openOrder(order.dataset.order);const action=e.target.closest('[data-order-action]');if(action)orderAction(action.dataset.id,action.dataset.orderAction)});
$('#google-login-btn').addEventListener('click',login);$('#logout-btn').addEventListener('click',logout);$('#onboarding-logout-btn').addEventListener('click',logout);$('#business-form').addEventListener('submit',createBusiness);$('#location-btn').addEventListener('click',requestLocation);$('#shop-toggle').addEventListener('click',toggleShop);$('#add-product-btn').addEventListener('click',()=>{resetProductForm();openModal('product-modal')});$('#product-form').addEventListener('submit',saveProduct);$('#product-search').addEventListener('input',e=>{state.productFilter=e.target.value;renderProducts()});$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.orderFilter=b.dataset.filter;renderOrders()}));$$('[data-stock-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-stock-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.stockFilter=b.dataset.stockFilter;renderInventory()}));$('#owner-phone').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,10));

onAuthStateChanged(auth,async user=>{state.user=user;if(!user){showScreen('login-screen');return}showScreen('loading-screen');try{const ready=await loadMerchant();if(!ready){hydrateOnboarding();showScreen('onboarding-screen');return}hydrateApp();startRealtime();showScreen('app-screen')}catch(e){console.error(e);toast('Merchant data could not load. Check Firestore rules.',true);showScreen('login-screen')}});
